"""
Setup script for building installer
Auto-generated by MSI Builder GUI
"""

import sys
import os
from cx_Freeze import setup, Executable

# Application metadata
APP_NAME = "App Change Image To .Ico File"
APP_VERSION = "1.0"
APP_DESCRIPTION = """Đây là app chuyển đổi"""
APP_AUTHOR = "Hoàng Thịnh"

# Dependencies to include
build_exe_options = {
    "packages": ["tkinter", "PIL", "os", "sys", "src", "requests", "packaging", "hashlib", "zipfile"],
    "include_files": [],
    # Explicitly include common Pillow modules so cx_Freeze bundles them.
    "includes": [
        "PIL",
        "PIL.Image",
        "PIL.ImageFile",
        "PIL.ImageTk",
    ],
    "excludes": ["unittest", "email", "html", "http", "urllib", "xml", "test"],
    "optimize": 2,
    "include_msvcr": True,
    "zip_include_packages": ["*"],
    "zip_exclude_packages": [],
    "bin_includes": [],  # Automatically includes python311.dll
    "bin_excludes": [],
}

# MSI build options
ICON_PATH = os.path.abspath("output2.ico") if os.path.exists("output2.ico") else None

bdist_msi_options = {
    "add_to_path": False,
    "initial_target_dir": r"[ProgramFilesFolder]\App Change Image To .Ico File",
    # If an icon file exists in the project root use it, otherwise don't set install_icon
    **({"install_icon": ICON_PATH} if ICON_PATH else {}),
}

# Base for Windows GUI application
base = None
if sys.platform == "win32":
    base = "Win32GUI"

# Executables to build
executables = [
    Executable(
        "src/gui_app.py",
        base=base,
        target_name="App Change Image To .Ico File.exe",
        icon=ICON_PATH if ICON_PATH else None,
        shortcut_name="App Change Image To .Ico File",
        shortcut_dir='DesktopFolder',
    ),
]

# Setup configuration
setup(
    name=APP_NAME,
    version=APP_VERSION,
    description=APP_DESCRIPTION,
    author=APP_AUTHOR,
    options={
        "build_exe": build_exe_options,
        "bdist_msi": bdist_msi_options,
    },
    executables=executables,
)

def _check_pillow():
    try:
        import PIL  # noqa: F401
    except Exception:
        msg = (
            "Pillow (PIL) is not installed in the active environment.\n"
            "Please install it before running this setup on Windows.\n"
            "Recommended command:\n    pip install -r requirements.txt\n"
            "Or:\n    pip install Pillow\n"
        )
        print(msg, file=sys.stderr)
        # Abort early with a non-zero exit code to avoid running cx_Freeze with a missing dependency.
        sys.exit(1)
    return True


if __name__ == "__main__":
    # When invoked directly, give a helpful message if Pillow isn't available.
    _check_pillow()
