"""
Setup script for building installer
Auto-generated by MSI Builder GUI
"""

import sys
from cx_Freeze import setup, Executable

# Application metadata
APP_NAME = "App Change Image To .Ico File"
APP_VERSION = "1.0"
APP_DESCRIPTION = """Đây là app chuyển đổi"""
APP_AUTHOR = "Hoàng Thịnh"

# Dependencies to include
build_exe_options = {
    "packages": ["tkinter", "PIL", "os", "sys", "src", "requests", "packaging", "hashlib", "zipfile"],
    "include_files": [],
    "excludes": ["unittest", "email", "html", "http", "urllib", "xml", "test"],
    "optimize": 2,
    "include_msvcr": True,
    "zip_include_packages": ["*"],
    "zip_exclude_packages": [],
    "bin_includes": [],  # Automatically includes python311.dll
    "bin_excludes": [],
}

# MSI build options
bdist_msi_options = {
    "add_to_path": False,
    "initial_target_dir": r"[ProgramFilesFolder]\App Change Image To .Ico File",
    "install_icon": "C:/App-Change-Image-to-.ico-file/output2.ico",
}

# Base for Windows GUI application
base = None
if sys.platform == "win32":
    base = "Win32GUI"

# Executables to build
executables = [
    Executable(
        "src/gui_app.py",
        base=base,
        target_name="App Change Image To .Ico File.exe",
        icon="C:/App-Change-Image-to-.ico-file/output2.ico",
        shortcut_name="App Change Image To .Ico File",
        shortcut_dir='DesktopFolder',
    ),
]

# Setup configuration
setup(
    name=APP_NAME,
    version=APP_VERSION,
    description=APP_DESCRIPTION,
    author=APP_AUTHOR,
    options={
        "build_exe": build_exe_options,
        "bdist_msi": bdist_msi_options,
    },
    executables=executables,
)
